### ISSUE TITLE
Add syntax highlighting like other docs

### ISSUE THREAD

**Issue by yaili** [canonical-webteam/example-js#11]
Would it be possible to have syntax highlighting in our code blocks like other docs?

Currently: https://docs.vanillaframework.io/en/patterns/navigation

Ideal: https://docs.ubuntu.com/maas/2.1/en/installconfig-lxd-install#create-a-lxc-profile-for-maas

**Comment by anthonydillon** [comment]
Great idea, something I'll look into.
