### ISSUE TITLE
Can we use same labels as other repos?

### ISSUE THREAD

**Issue by yaili** [canonical-webteam/example-js#12]
Labels used in other projects: https://github.com/vanilla-framework/vanilla-brochure-theme/labels

We probably don't need working group (WG:*) labels here though.

**Comment by barrymcgee** [comment]
Done: https://github.com/ubuntudesign/example-js/labels

**Comment by barrymcgee** [comment]
@nottrobin I can't seem to close this issue even though it's complete?

**Comment by nottrobin** [comment]
Sorry @barrymcgee, forgot to invite you to canonical-webteam. Have now, you can accept at https://github.com/canonical-webteam. Closing.
