### ISSUE TITLE
Automatically trim whitespace in example code

### ISSUE THREAD

**Issue by yaili** [canonical-webteam/example-js#20]
It would be good if the whitespace above/below code examples could be automatically trimmed. Right now it isn't, so in most examples there is too much top/bottom padding, which doesn't look great: example - https://docs.vanillaframework.io/en/base/forms

**Comment by anthonydillon** [comment]
This has been complete but was not released. It will be in the next release today. 

Also dup of https://github.com/canonical-webteam/example-js/issues/14
