### ISSUE TITLE
The default height is too large

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/example-js#22]
The default height of the iframe seems to be `160px` which is too big. Set it lower or not at all.

**Comment by deadlight** [comment]
Whoever picks this up should speak to a relevant designer to get the latest thoughts on this

**Comment by kwm14** [comment]
@anthonydillon is this issue referring to the Code block or Component example?

**Comment by anthonydillon** [comment]
There is a min height to the examples but for buttons for example it's too big.

**Comment by kwm14** [comment]
@anthonydillon Ok thanks. If we set no max-height to the iFrame will all examples work fine/be viewable?
