### ISSUE TITLE
Copy to clipboard icon for code snippets

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/example-js#25]
We should use the copy to clipboard icon that we're using.

**Comment by deadlight** [comment]
@anthonydillon can you clarify the details of this one, please? Which icon? Where are we using it?

**Comment by anthonydillon** [comment]
@Greggless @kwm14 would you mind commenting on this from a design/UX perspective?

**Comment by anthonydillon** [comment]
Here is the wireframe for pattern:
![card example](https://user-images.githubusercontent.com/23459065/28663055-29850cd0-72b4-11e7-9a2b-9d7f5a9a5c2f.png)

**Comment by kwm14** [comment]
@anthonydillon @deadlight 

The copy to clipboard icon was recently designed by Spencer based on the issue [here](https://github.com/ubuntudesign/vanilla-design/issues/24), it's currently being used in build.snapcraft.io, Juju and MAAS.

Copy to clipboard icon: https://assets.ubuntu.com/v1/ae4856d4-copy-to-clipboard-16.svg

**build.snapcraft.io**
![screen shot 2017-09-13 at 14 51 16](https://user-images.githubusercontent.com/17748020/30381001-14cefb16-9893-11e7-958e-b952f34858a9.png)

**Juju**
![screen shot 2017-09-13 at 14 47 17](https://user-images.githubusercontent.com/17748020/30380830-8fd6e1b2-9892-11e7-85e0-9a5273d1a62c.png)

**MAAS**
![screen shot 2017-09-13 at 15 01 33](https://user-images.githubusercontent.com/17748020/30381521-8eae9f26-9894-11e7-8bfe-c6e679cf28df.png)

**Comment by kwm14** [comment]
## Updated visual

Updated design to use max-height decided in issue #27 and new Code snippet icon. Design reviewed and signed-off by Spencer.

### Default state
![docs-copy-code-default](https://user-images.githubusercontent.com/17748020/35622319-4e01e902-067f-11e8-95f4-b7da85a6f2ac.png)

### Hover state
![docs-copy-code-hover](https://user-images.githubusercontent.com/17748020/35622322-56a51304-067f-11e8-8995-d5b29c3de12a.png)

**Comment by kwm14** [comment]
I will create a separate issue for design to be built and implemented
