### ISSUE TITLE
Toggle to display different viewports

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/example-js#26]
Toggle to display different viewports is nice. Display only options that are lower than the current viewport width.

**Comment by deadlight** [comment]
@anthonydillon are there design assets/patterns for this?

**Comment by anthonydillon** [comment]
@Greggless @kwm14 would you mind commenting on this from a design/UX perspective?

**Comment by anthonydillon** [comment]
This is, in fact, a duplicate of https://github.com/canonical-webteam/example-js/issues/19
