### ISSUE TITLE
Limited code blocks height

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/example-js#27]
Code blocks should have a maximum number of lines before it displays the see more.

**Comment by deadlight** [comment]
@anthonydillon do we have any guidance on how many lines this should be?

**Comment by anthonydillon** [comment]
@Greggless @kwm14 would you mind commenting on this from a design/UX perspective?

**Comment by anthonydillon** [comment]
Here is the wireframe for pattern:
![card example](https://user-images.githubusercontent.com/23459065/28663055-29850cd0-72b4-11e7-9a2b-9d7f5a9a5c2f.png)

**Comment by kwm14** [comment]
@anthonydillon @deadlight 

I'm not sure I can suggest a character limit but implemented in build.snapcraft.io is the 'Add repos' dialog (seen below) it has a fixed height @350px and content scrolls within, it also scales when reaching medium and small breakpoints.

![screen shot 2017-09-13 at 14 34 32](https://user-images.githubusercontent.com/17748020/30380247-07e27920-9891-11e7-944d-828dc570d4a6.png)

I know we're going to be using this dialog pattern in MAAS for hardware testing, so this could be a good route to take for first pass. @Greggless any thoughts on that proposal?

**Comment by kwm14** [comment]
New issue created for build as new design solution created [here](https://github.com/canonical-webteam/example-js/issues/25). New build ticket [here](https://github.com/canonical-webteam/example-js/issues/30).
